# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

twoStateSufficientStatistics <- function(treeEdges, tipStates, branchLengths, lambda_01, lambda_10, rootDist) {
    .Call('indorigin_twoStateSufficientStatistics', PACKAGE = 'indorigin', treeEdges, tipStates, branchLengths, lambda_01, lambda_10, rootDist)
}

twoStateCompleteDataLogPosterior <- function(suffStat, lambda_01, lambda_10, prior_alpha_01, prior_beta_01, prior_alpha_10, prior_beta_10) {
    .Call('indorigin_twoStateCompleteDataLogPosterior', PACKAGE = 'indorigin', suffStat, lambda_01, lambda_10, prior_alpha_01, prior_beta_01, prior_alpha_10, prior_beta_10)
}

twoStatePhyloGibbsSampler <- function(treeEdges, cubeDims, branchLengths, rootDist, tipStates, initial_lambda_01, initial_lambda_10, prior_alpha_01, prior_beta_01, prior_alpha_10, prior_beta_10, mcmcSize, mcmcBurnin, mcmcSubsample) {
    .Call('indorigin_twoStatePhyloGibbsSampler', PACKAGE = 'indorigin', treeEdges, cubeDims, branchLengths, rootDist, tipStates, initial_lambda_01, initial_lambda_10, prior_alpha_01, prior_beta_01, prior_alpha_10, prior_beta_10, mcmcSize, mcmcBurnin, mcmcSubsample)
}

